fpath=(~/.zsh/completion $fpath)

# zsh Completion scripts
zstyle ':completion:*' completer _oldlist _expand _complete _ignored _correct _approximate
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' file-sort name
zstyle ':completion:*' ignore-parents parent
zstyle ':completion:*' matcher-list 'r:|[._-]=* r:|=*'
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:kill:*' force-list always
zstyle ':completion:*' format "$green%B---- %d ----%b"
zstyle ':completion:*:descriptions'    format $'%{\e[0;31m%}searching for %B%d%b%{\e[0m%}'
zstyle ':completion:*:messages' format '%B%U%d%u%b'
zstyle ':completion:*:warnings' format "%B$red%}no match for $white%d%b"
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu yes select
zstyle ':completion:*:*:git:*' script ~/dotfiles/oh-my-zsh/plugins/gitfast/git-completion.bash

source ${HOME}/.oh-my-zsh-config

export PATH=/usr/bin:/usr/local/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:~/dotfiles/git-achievements:~/.cabal/bin:~/.xmonad/bin
export PYTHONPATH=/usr/local/bin:${PYTHONPATH}

export GIT_EDITOR=/usr/bin/vim

export EDITOR=/usr/bin/vim
# Git achievements! \o/

alias git="git-achievements"
# zsh Powerline Stuff
POWERLINE_FULL_CURRENT_PATH="true"

setopt extendedglob

PATH=$HOME/.local-installs/bin:$HOME/.cabal/bin:$PATH:$HOME/.rvm/bin:/home/miles/.gem/ruby/2.0.0/bin # Add RVM to PATH for scripting

# added by travis gem
[ -f /home/miles/.travis/travis.sh ] && source /home/miles/.travis/travis.sh

# use nvm
[ -f /home/miles/.nvm/nvm.sh ] && source /home/miles/.nvm/nvm.sh
