source ${HOME}/.oh-my-zsh-config

export PATH=$PATH:~/dotfiles/git-achievements
export PYTHONPATH=/usr/local/bin:${PYTHONPATH}

# Git achievements! \o/

alias git="git-achievements"

# Virtualenv stuff (for Python)

export WORKON_HOME=~/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true
