source ${HOME}/.oh-my-zsh-config

export PATH=/usr/bin:/usr/local/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:~/dotfiles/git-achievements
export PYTHONPATH=/usr/local/bin:${PYTHONPATH}
export EDITOR=/usr/local/Cellar/macvim/7.3-64/MacVim.app/Contents/MacOS/Vim

# Git achievements! \o/

alias git="git-achievements"

# Virtualenv stuff (for Python)

export WORKON_HOME=~/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true

# zsh Powerline Stuff
POWERLINE_FULL_CURRENT_PATH="true"

# zsh Completion scripts
zstyle ':completion:*' completer _oldlist _expand _complete _ignored _correct _approximate
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' file-sort name
zstyle ':completion:*' ignore-parents parent
zstyle ':completion:*' matcher-list 'r:|[._-]=* r:|=*'
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:kill:*' force-list always
zstyle ':completion:*' format "$green%B---- %d ----%b"
zstyle ':completion:*:descriptions'    format $'%{\e[0;31m%}searching for %B%d%b%{\e[0m%}'
zstyle ':completion:*:messages' format '%B%U%d%u%b'
zstyle ':completion:*:warnings' format "%B$red%}no match for $white%d%b"
zstyle ':completion:*' group-name '' 
zstyle ':completion:*' menu yes select

setopt extendedglob

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
