#!/usr/bin/env zsh

echo "Linking vimfiles"
if [ ! -d ~/.vim ]; then
    ln -s ~/dotfiles/vimfiles ~/.vim
else
    if [ -L ~/.vim ]; then
        echo "Failed. Symlink at ~/.vim already exists!"
    else
        echo "Failed. Existing directory at ~/.vim, please remove before continuing"
    fi
fi
for i in `ls ~/dotfiles/dotfiles|xargs`; do
    if [[ $i != $1 ]]; then
        echo "Linking $i..."
        ln -s ~/dotfiles/dotfiles/$i ~/.$i
    fi
done
echo 'Done!'
